<?php
    include("sql/databaseconnaction.php");
    include("model/Country.php");
    include("model/Property.php");
    include("layout/head.php");
    include("router.php");      
?>
<body>
    <?php
        include("layout/header.php");
        include("layout/nav.php");
    ?>    
    <main>
    <?php
        include($view);
    ?>
    </main>
    <?php
        include("layout/footer.php");
    ?>
</body>
